# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcedamicQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DegreeName', models.CharField(max_length=100)),
                ('Institution', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('PhoneNo', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password', models.CharField(max_length=100)),
                ('UserName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiCode.Contractor')),
            ],
        ),
        migrations.CreateModel(
            name='OtherExperiences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=1000)),
                ('UserName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiCode.Contractor')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SkillCatagory', models.CharField(max_length=100)),
                ('SkillName', models.CharField(max_length=1000)),
                ('SkillLevel', models.CharField(max_length=100)),
                ('UserName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiCode.Contractor')),
            ],
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.AddField(
            model_name='acedamicqualification',
            name='UserName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiCode.Contractor'),
        ),
    ]
