# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCode', '0003_auto_20170724_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='acedamicqualification',
            name='EndYear',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='acedamicqualification',
            name='Percentile',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='acedamicqualification',
            name='StartYear',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='acedamicqualification',
            name='DegreeName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='acedamicqualification',
            name='Institution',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='acedamicqualification',
            name='UserName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='ApiCode.Contractor'),
        ),
    ]
