# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCode', '0004_auto_20170724_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=100, null=True)),
                ('Designation', models.CharField(max_length=100, null=True)),
                ('StartYear', models.FloatField(null=True)),
                ('EndYear', models.FloatField(null=True)),
                ('Description', models.CharField(max_length=1000, null=True)),
                ('UserName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiCode.Contractor')),
            ],
        ),
    ]
