# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCode', '0005_workexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressYourself',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=1000)),
                ('UserName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiCode.Contractor')),
            ],
        ),
    ]
