# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCode', '0006_expressyourself'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
    ]
