# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCode', '0008_companyname_degreename_designation_skillcatagory_skillname'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCatagories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(max_length=100)),
                ('values', models.CharField(max_length=10000)),
            ],
        ),
    ]
