# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCode', '0009_jobcatagories'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobcatagory', models.CharField(max_length=100)),
                ('jobname', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('files', models.CharField(max_length=100)),
                ('skillsneeded', models.CharField(max_length=1000)),
                ('expriencelevel', models.CharField(max_length=100)),
                ('jobtype', models.CharField(max_length=100)),
                ('UserName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiCode.Contractor')),
            ],
        ),
    ]
