# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCode', '0010_postjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='completiontime',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='postjob',
            name='status',
            field=models.FloatField(null=True),
        ),
    ]
