# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCode', '0012_postjob_posttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='UserName',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='UserName',
            field=models.ForeignKey(db_column='UserName', on_delete=django.db.models.deletion.CASCADE, to='ApiCode.Contractor', to_field='UserName'),
        ),
    ]
