# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCode', '0014_auto_20170801_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='UserName',
            field=models.CharField(max_length=100),
        ),
    ]
