# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCode', '0016_auto_20170801_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='UserType',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
