# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCode', '0017_login_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='Password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
