# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCode', '0018_contractor_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='Password',
            field=models.CharField(max_length=100),
        ),
    ]
