# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCode', '0020_auto_20170802_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractor',
            old_name='Type',
            new_name='UserType',
        ),
    ]
