# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCode', '0021_auto_20170802_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjob',
            name='UserName',
            field=models.ForeignKey(db_column='UserName', on_delete=django.db.models.deletion.CASCADE, to='ApiCode.Contractor', to_field='UserName'),
        ),
    ]
