# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCode', '0022_auto_20170802_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Freelancer', models.CharField(max_length=100)),
                ('jobcatagory', models.CharField(max_length=100)),
                ('jobname', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('files', models.CharField(max_length=100)),
                ('skillsneeded', models.CharField(max_length=1000)),
                ('expriencelevel', models.CharField(max_length=100)),
                ('completiontime', models.FloatField(null=True)),
                ('status', models.FloatField(null=True)),
                ('jobtype', models.CharField(max_length=100)),
                ('posttype', models.FloatField(null=True)),
                ('Id', models.ForeignKey(db_column='Id', on_delete=django.db.models.deletion.CASCADE, to='ApiCode.PostJob')),
                ('UserName', models.ForeignKey(db_column='UserName', on_delete=django.db.models.deletion.CASCADE, to='ApiCode.Contractor', to_field='UserName')),
            ],
        ),
    ]
