# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCode', '0024_auto_20170804_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acedamicqualification',
            name='DegreeName',
        ),
        migrations.RemoveField(
            model_name='acedamicqualification',
            name='EndYear',
        ),
        migrations.RemoveField(
            model_name='acedamicqualification',
            name='StartYear',
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='EndYear',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='StartYear',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
