# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCode', '0026_auto_20170804_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='acedamicqualification',
            name='DegreeName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='acedamicqualification',
            name='EndYear',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='acedamicqualification',
            name='StartYear',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
