# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCode', '0027_auto_20170804_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstTimeLogin1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firsttime', models.BooleanField(default=True)),
                ('UserName', models.ForeignKey(db_column='UserName', on_delete=django.db.models.deletion.CASCADE, to='ApiCode.Contractor', to_field='UserName')),
            ],
        ),
    ]
