# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCode', '0029_auto_20170805_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressyourself',
            name='Resume',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
