# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCode', '0032_auto_20170807_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gigs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=1000, null=True)),
                ('Image1', models.ImageField(null=True, upload_to=b'')),
                ('Image2', models.ImageField(null=True, upload_to=b'')),
                ('Image3', models.ImageField(null=True, upload_to=b'')),
                ('UserName', models.ForeignKey(db_column='UserName', on_delete=django.db.models.deletion.CASCADE, to='ApiCode.Contractor', to_field='UserName')),
            ],
        ),
    ]
