# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCode', '0034_auto_20170820_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutename',
            name='Name',
            field=models.CharField(max_length=1000000),
        ),
    ]
