# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-11 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCode', '0039_auto_20170911_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigsimages',
            name='GigId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='ApiCode.Gigs'),
        ),
    ]
