# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-18 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCode', '0040_auto_20170911_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigsfaq',
            name='GigId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq', to='ApiCode.Gigs'),
        ),
        migrations.AlterField(
            model_name='gigsrequirements',
            name='GigId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='ApiCode.Gigs'),
        ),
        migrations.AlterField(
            model_name='gigssearchterms',
            name='GigId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searchterms', to='ApiCode.Gigs'),
        ),
    ]
