# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-21 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCode', '0041_auto_20170918_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserType', models.CharField(max_length=1000, null=True)),
                ('Catagory', models.CharField(max_length=1000, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=1000, null=True)),
                ('Option1', models.CharField(max_length=1000, null=True)),
                ('Option2', models.CharField(max_length=1000, null=True)),
                ('Option3', models.CharField(max_length=1000, null=True)),
                ('Option4', models.CharField(max_length=1000, null=True)),
                ('Answer', models.IntegerField(null=True)),
                ('Catagory', models.ForeignKey(db_column='Catagory', on_delete=django.db.models.deletion.CASCADE, to='ApiCode.Test', to_field='Catagory')),
            ],
        ),
        migrations.CreateModel(
            name='TestResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Percentage', models.FloatField(null=True)),
                ('Catagory', models.ForeignKey(db_column='Catagory', on_delete=django.db.models.deletion.CASCADE, to='ApiCode.Test', to_field='Catagory')),
                ('UserName', models.ForeignKey(db_column='UserName', on_delete=django.db.models.deletion.CASCADE, to='ApiCode.Contractor', to_field='UserName')),
            ],
        ),
    ]
