# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-09 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCode', '0043_auto_20170921_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bidder', models.CharField(max_length=1000, null=True)),
                ('BidPrize', models.FloatField(null=True)),
                ('Days', models.IntegerField(null=True)),
                ('Title', models.CharField(max_length=1000, null=True)),
                ('BidOwner', models.ForeignKey(db_column='UserName', on_delete=django.db.models.deletion.CASCADE, to='ApiCode.Contractor', to_field='UserName')),
                ('JobId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiCode.PostJob')),
            ],
        ),
        migrations.CreateModel(
            name='GigsReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reviewer', models.CharField(max_length=1000, null=True)),
                ('Review', models.CharField(max_length=1000, null=True)),
                ('GigId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ApiCode.Gigs')),
                ('UserName', models.ForeignKey(db_column='UserName', on_delete=django.db.models.deletion.CASCADE, to='ApiCode.Contractor', to_field='UserName')),
            ],
        ),
    ]
