# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-10 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCode', '0044_bid_gigsreviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppliedJobId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliedjob', to='ApiCode.PostJob')),
                ('JobApplier', models.ForeignKey(db_column='UserName', on_delete=django.db.models.deletion.CASCADE, to='ApiCode.Contractor', to_field='UserName')),
            ],
        ),
        migrations.AlterField(
            model_name='bid',
            name='JobId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='ApiCode.PostJob'),
        ),
    ]
