# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-11 11:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCode', '0046_auto_20171011_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='budget',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='postjob',
            name='createdat',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 10, 11, 11, 59, 49, 193022, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postjob',
            name='negotiatable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postjob',
            name='taken',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='appliedjobs',
            name='AppliedJobId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliedjob', to='ApiCode.PostJob', unique=True),
        ),
    ]
