# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-13 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCode', '0048_auto_20171012_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='BidDays',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together=set([('Bidder', 'JobId')]),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set([('UserName', 'Id')]),
        ),
    ]
