# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-16 13:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCode', '0050_remove_skills_skillcatagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='acedamicqualification',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 10, 16, 13, 8, 3, 809238, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acedamicqualification',
            name='Deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expressyourself',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 10, 16, 13, 8, 24, 126350, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expressyourself',
            name='Deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otherexperiences',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 10, 16, 13, 10, 24, 334733, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherexperiences',
            name='Deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skills',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 10, 16, 13, 10, 34, 748096, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skills',
            name='Deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 10, 16, 13, 10, 51, 980134, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workexperience',
            name='Deleted',
            field=models.BooleanField(default=False),
        ),
    ]
