# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-18 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCode', '0054_auto_20171018_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='CompanyName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='Description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='Designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='EndYear',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='StartYear',
            field=models.DateField(),
        ),
    ]
