# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-19 05:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCode', '0055_auto_20171018_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='UserType',
        ),
        migrations.AddField(
            model_name='contractor',
            name='AcountActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 10, 19, 5, 21, 36, 185655, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractor',
            name='Deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractor',
            name='FirstTimeLogin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='Country',
            field=models.CharField(default=datetime.datetime(2017, 10, 19, 5, 21, 44, 984154, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contractor',
            name='Email',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='Name',
            field=models.CharField(max_length=1000),
        ),
    ]
