# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-19 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCode', '0057_auto_20171019_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='FirstTimeLogin',
            field=models.BooleanField(default=True),
        ),
    ]
