# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-30 14:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MessageText', models.CharField(max_length=10000)),
                ('Seen', models.BooleanField(default=False)),
                ('Deleted', models.BooleanField(default=False)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('Reciever', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomNo', models.CharField(max_length=1000, unique=True)),
                ('Deleted', models.BooleanField(default=False)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('HFW', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='HFW', to=settings.AUTH_USER_MODEL)),
                ('LFW', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='LFW', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='Room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='websocketchannel.Room'),
        ),
        migrations.AddField(
            model_name='message',
            name='Sender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set([('HFW', 'LFW')]),
        ),
    ]
