# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-01 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websocketchannel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='Reciever',
        ),
    ]
