# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-25 10:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gigs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Catagory', models.CharField(max_length=100, null=True)),
                ('Title', models.CharField(max_length=100, null=True)),
                ('Description', models.CharField(max_length=1000, null=True)),
                ('Time', models.DateTimeField(null=True)),
                ('Complete', models.BooleanField(default=False)),
                ('Favourite', models.BooleanField(default=False)),
                ('Deleted', models.BooleanField(default=False)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GigsFAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=1000, null=True)),
                ('Answer', models.CharField(max_length=1000, null=True)),
                ('GigId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq', to='Showcase.Gigs')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GigsImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(null=True, upload_to=b'')),
                ('GigId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='Showcase.Gigs')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GigsRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Requirement', models.CharField(max_length=100, null=True)),
                ('IsMandatory', models.BooleanField(default=False)),
                ('GigId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='Showcase.Gigs')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GigsReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reviewer', models.CharField(max_length=1000, null=True)),
                ('Review', models.CharField(max_length=1000, null=True)),
                ('GigId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Showcase.Gigs')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GigsSearchTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SearchTerms', models.CharField(max_length=1000, null=True)),
                ('GigId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searchterms', to='Showcase.Gigs')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
