# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-04 10:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Showcase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GigsPrize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MinPrize', models.IntegerField(null=True)),
                ('MaxPrize', models.IntegerField(null=True)),
                ('Days', models.IntegerField(null=True)),
                ('GigId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prize', to='Showcase.Gigs')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='gigsreviews',
            name='Reviewer',
        ),
    ]
