# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-23 11:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BidPrize', models.FloatField(null=True)),
                ('Days', models.IntegerField(null=True)),
                ('Title', models.CharField(max_length=1000, null=True)),
                ('Status', models.IntegerField(null=True)),
                ('ExpertGuarantee', models.BooleanField(default=False)),
                ('SponsorMyBid', models.BooleanField(default=False)),
                ('HighlightMyBid', models.BooleanField(default=False)),
                ('Deleted', models.BooleanField(default=False)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('BidOwner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bidowner', to=settings.AUTH_USER_MODEL)),
                ('Bidder', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bidder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Deleted', models.BooleanField(default=False)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobCatagories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Catagory', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobSubCatagories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubCatagory', models.CharField(max_length=10000)),
                ('Catagory', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Bidding.JobCatagories')),
            ],
        ),
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobCatagory', models.CharField(max_length=100)),
                ('JobSubCatagory', models.CharField(max_length=100)),
                ('JobName', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=1000)),
                ('SkillsNeeded', models.CharField(max_length=1000)),
                ('ExprienceLevel', models.CharField(max_length=100)),
                ('CompletionTime', models.FloatField(null=True)),
                ('Status', models.FloatField(null=True)),
                ('JobType', models.CharField(max_length=100)),
                ('PostType', models.FloatField(null=True)),
                ('Taken', models.IntegerField(default=None, null=True)),
                ('Budget', models.FloatField(default=None, null=True)),
                ('Negotiatable', models.BooleanField(default=False)),
                ('BidDays', models.IntegerField(null=True)),
                ('Deleted', models.BooleanField(default=False)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkillsNeeded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SkillName', models.CharField(max_length=100)),
                ('JobId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Bidding.PostJob')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bookmark',
            name='Id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Bidding.PostJob'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='JobId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='Bidding.PostJob'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set([('user', 'Id')]),
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together=set([('Bidder', 'JobId')]),
        ),
    ]
